Report libpq error code for errors with no message
Instead of:

    DatabaseError: error with no message from the libpq

raise a message like:

    DatabaseError: error code PGRES_COPY_BOTH with no error message from
    libpq

(In this particular case PGRES_COPY_BOTH isn't actually an error, but
psycopg2 doesn't understand it and should treat it that way.)

Fixes #352